Fix removal of foreign key fields in MySQL
Without the patch test fails like this:

    OperationalError: (1025, "Error on rename of './test_myapp/test_rfk_rider' to './test_myapp/#sql2-3398-2e8' (errno: 152)")

In MySQL you explicitly have to remove the constraint first.