Fixed inaccuracy in runserver outpout.
Using runserver looks like:

    >>> ./manage.py runserver
    Validating models...

    0 errors found
    Django version 1.4, using settings 'test_project.settings'
    Development server is running at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.

The problem is that if the port is already bound, it will look like:

    >>> ./manage.py runserver
    Validating models...

    0 errors found
    Django version 1.4, using settings 'test_project.settings'
    Development server is running at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    Error: That port is already in use.

Which misleads the system administrator who may think that runserver
double bound that port.

With this patch, it looks like:

    >>> ./manage.py runserver
    Validating models...

     0 errors found
     Django version 1.5.dev20120521232858, using settings 'test_project.settings'
     Development server is starting at http://127.0.0.1:8000/
     Quit the server with CONTROL-C.
     Error: That port is already in use.

Which is accurate.

Credit to William Waisse for reporting the issue.