Bugfix: Support Python 3.7
Fix for:

```
  File ".../site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
```
And yes it's really only two square brackets missing!