[5.0.x] Updated source translation catalogs.
This work includes the updating of the translations catalog for JS files. The
catalog was generated with this command:

django-admin makemessages -l en --domain=djangojs -i views/templates/i18n_catalog.js

The `views/templates/i18n_catalog.js` file had to be ignored because otherwise
the command would fail as follows:

xgettext: warning: msgid '' is used without plural and with plural.
                   ./views/templates/i18n_catalog.js:52: Here is the occurrence without plural.
                   ./views/templates/i18n_catalog.js:60: Here is the occurrence with plural.
                   Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
CommandError: errors happened while running msguniq
/home/nessita/fellowship/django/django/conf/locale/djangojs.pot:22: context separator <EOT> within string
/home/nessita/fellowship/django/django/conf/locale/djangojs.pot:23: context separator <EOT> within string
msguniq: found 2 fatal errors