Skipped tests involving 1-element GeometryCollections on Oracle 23.9.
Because these Oracle versions unpack 1-element collections, LayerMapping
unexpectedly received single geometries and failed when saving:

  File "/django/source/django/contrib/gis/utils/layermapping.py", line 663, in _save
    geom.add(g)
    ^^^^^^^^
AttributeError: 'Polygon' object has no attribute 'add'

https://forums.oracle.com/ords/apexds/post/23ai-sdo-geometry-converts-1-element-multipolygon-to-polygo-3474