Refs #32833 -- inline ContentType.model_class() in .get_for_models()
On migrations the versioned content type objects does not implement
model_class(), when get_for_models() is called on manager and some
content type is not in cache a query is made to load them from DB,
if at last one is found then ContentType.model_class() is called on
loaded objects which causes AttributeError to be raised.

Regression in 0b8e75cce99a6788307bb63899e8e0cffa81beea