Document bcrypt v5 truncation behavior
Failure to first truncate passwords to 72 characters can cause 500s on
error registration for any Django application using bcrypt v5.

This tweaks the hasher docstring to better document how different bcrypt
versions handle truncation.

Users of `BCryptPasswordHasher` should likely truncate passwords
*before* invoking `check_password()`.

bcrypt v5
=========
The Python library bcrypt released a new major version on Sept 25:
https://github.com/pyca/bcrypt/blob/d8a36672bf65c44fb9b2dfc1114de113b2005dda/CHANGELOG.rst

As part of the v5 release, hashing longer passwords now raises a
`ValueError` instead of silently truncating to 72 bytes:

> Passing `hashpw` a password longer than 72 bytes now raises a
> `ValueError.` Previously the password was silently truncated,
> following the behavior of the original OpenBSD `bcrypt` implementation.

Remove the recommendation of pre-hashing
========================================
I'm not a cryptographer, but it's perhaps best to remove the advice
suggesting users to instead favor `BCryptSHA256PasswordHasher`. Passing
passwords through SHA-256 before bycrpt is vulnerable to password shucking:
https://www.scottbrady.io/authentication/beware-of-password-shucking

Instead, we can merely remove the advice & document differences.

Demonstration of v4 versus v5 behavior
======================================

```python
from django.contrib.auth.models import AbstractBaseUser

class User(AbstractBaseUser):  # Normally just settings.AUTH_USER_MODEL
    pass

class DemoTest(TestCase):
    def test_truncation():
        user = User()

        with self.settings(PASSWORD_HASHERS=["django.contrib.auth.hashers.BCryptPasswordHasher"]):
            user.check_password(73 * 'x')
```

On newer bcrypt, we get:
```
ValueError: password cannot be longer than 72 bytes, truncate manually if necessary (e.g. my_password[:72])
```

bcrypt version 4 or older simply truncated silently to 72 bytes.

Previous documentation efforts
==============================
This docstring was originally written in 2013:
https://github.com/django/django/pull/958/

A followup PR then documented the truncation behavior:
https://github.com/django/django/pull/962/

IN 2018, `BCryptPasswordHasher` was removed from `PASSWORD_HASHERS`,
removing the documentation about password truncation:
https://github.com/django/django/pull/9728