Ensure that parallel test error can be unpickled.
Until now we've only been checking whether the error can be pickled, but
some errors get through that and then fail during unpickling in the main
process causing the Pool management code to blow up.

One example of error like that is botocore.exceptions.ClientError
which pickles as "ClientError(message)", but its initializer is actually
ClientError(response, operation_name). This causes the parallel test
runner to fail with:

multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'operation_name'