Fix router examples allow_migrate crash
allow_migrate requires model parameter to have default value None, as described in reference documentation (same file but before examples):
https://docs.djangoproject.com/en/1.8/topics/db/multi-db/#allow_migrate

Otherwise it crashes with error:

File "c:\...\site-packages\django\db\utils.py", line 347, in allow_migrate
    allow = method(db, app_label, **hints)
TypeError: allow_migrate() takes exactly 4 arguments (3 given)