Fixed #35571 -- Store template_names as string
When passing pathlib.Path or pathlib.PosixPath as template names (because templates are in subdirectories, so pathlib seems reasonable to use) the assertTemplateUsed breaks as it performs a str.join on all template names without sanitizing them.

```
File "<stuff>/.local/lib/python3.12/site-packages/django/test/testcases.py", line 681, in _assert_template_used
    % (template_name, ", ".join(template_names)),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, PosixPath found
```

This causes a lot of confusion as it is quite hard to track down the Template that introduced the PosixPath.

This is one proposed solution for fixing this. I.e. trying to sanitize all template names when they are passed into the template engine, as this seems easier then trying to find all cases where the stringiness of the template name is assumed. Another approach would be to have an assert that the template name is a string, but this could possible break code that doesn't utilize the test framework.