Fix test_attribute_name_not_python_keyword inspectdb test
test_attribute_name_not_python_keyword (inspectdb.tests.InspectDBTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Jenkins\workspace\pull-requests-windows\database\sqlite3\label\windows\python\Python37\django\test\testcases.py", line 1206, in skip_wrapper
    return test_func(*args, **kwargs)
  File "C:\Jenkins\workspace\pull-requests-windows\database\sqlite3\label\windows\python\Python37\tests\inspectdb\tests.py", line 143, in test_attribute_name_not_python_keyword
    self.assertIn("parent = models.ForeignKey('self', models.DO_NOTHING)", output)
AssertionError: "parent = models.ForeignKey('self', models.DO_NOTHING)" not found in "# This is an auto-generated Django model module.\n# You'll have to do the following manually to clean this up:\n#   * Rearrange models' order\n#   * Make sure each model has one field with primary_key=True\n#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior\n#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table\n# Feel free to rename the models, but don't rename db_table values or field names.\nfrom django.db import models\n\n\nclass InspectdbColumntypes(models.Model):\n    big_int_field = models.BigIntegerField()\n    bool_field = models.BooleanField()\n    null_bool_field = models.BooleanField(blank=True, null=True)\n    char_field = models.CharField(max_length=10)\n    null_char_field = models.CharField(max_length=10, blank=True, null=True)\n    date_field = models.DateField()\n    date_time_field = models.DateTimeField()\n    decimal_field = models.DecimalField(max_digits=10, decimal_places=5)  # max_digits and decimal_places have been guessed, as this database handles decimal fields as float\n    email_field = models.CharField(max_length=254)\n    file_field = models.CharField(max_length=100)\n    file_path_field = models.CharField(max_length=100)\n    float_field = models.FloatField()\n    int_field = models.IntegerField()\n    gen_ip_address_field = models.CharField(max_length=39)\n    pos_int_field = models.PositiveIntegerField()\n    pos_small_int_field = models.PositiveSmallIntegerField()\n    slug_field = models.CharField(db_index=True, max_length=50)\n    small_int_field = models.SmallIntegerField()\n    text_field = models.TextField()\n    time_field = models.TimeField()\n    url_field = models.CharField(max_length=200)\n    uuid_field = models.CharField(max_length=32)\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_columntypes'\n\n\nclass InspectdbDigitsincolumnname(models.Model):\n    number_123 = models.CharField(db_column='123', max_length=11)  # Field renamed because it wasn't a valid Python identifier.\n    number_4extra = models.CharField(db_column='4extra', max_length=11)  # Field renamed because it wasn't a valid Python identifier.\n    number_45extra = models.CharField(db_column='45extra', max_length=11)  # Field renamed because it wasn't a valid Python identifier.\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_digitsincolumnname'\n\n\nclass InspectdbMessage(models.Model):\n    from_field = models.ForeignKey('InspectdbPeople', models.DO_NOTHING, db_column='from_id', db_index=True)  # Field renamed because it was a Python reserved word.\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_message'\n\n\nclass InspectdbPeople(models.Model):\n    name = models.CharField(max_length=255)\n    parent = models.ForeignKey('self', models.DO_NOTHING, db_index=True)\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_people'\n\n\nclass InspectdbPeopledata(models.Model):\n    people_pk = models.OneToOneField(InspectdbPeople, models.DO_NOTHING, primary_key=True)\n    ssn = models.CharField(max_length=11)\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_peopledata'\n\n\nclass InspectdbPeoplemoredata(models.Model):\n    people_unique = models.OneToOneField(InspectdbPeople, models.DO_NOTHING)\n    message = models.ForeignKey(InspectdbMessage, models.DO_NOTHING, db_index=True, blank=True, null=True)\n    license = models.CharField(max_length=255)\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_peoplemoredata'\n\n\nclass InspectdbSpecialTableName(models.Model):\n    field = models.IntegerField()\n    field_field = models.IntegerField(db_column='Field_')  # Field name made lowercase. Field renamed because it ended with '_'.\n    field_field_0 = models.IntegerField(db_column='Field__')  # Field name made lowercase. Field renamed because it contained more than one '_' in a row. Field renamed because it ended with '_'. Field renamed because of name conflict.\n    field_field_1 = models.IntegerField(db_column='__field')  # Field renamed because it contained more than one '_' in a row. Field renamed because it started with '_'. Field renamed because of name conflict.\n    prc_x = models.IntegerField(db_column='prc(%) x')  # Field renamed to remove unsuitable characters.\n    tamaño = models.IntegerField()\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_special.table name'\n\n\nclass InspectdbUniquetogether(models.Model):\n    field1 = models.IntegerField()\n    field2 = models.CharField(max_length=10)\n    from_field = models.IntegerField(db_column='from')  # Field renamed because it was a Python reserved word.\n    non_unique_column = models.IntegerField(db_column='non__unique_column')  # Field renamed because it contained more than one '_' in a row.\n    non_unique_column_0 = models.IntegerField(db_column='non_unique__column')  # Field renamed because it contained more than one '_' in a row. Field renamed because of name conflict.\n\n    class Meta:\n        managed = False\n        db_table = 'inspectdb_uniquetogether'\n        unique_together = (('non_unique_column', 'non_unique_column_0'), ('from_field', 'field1'), ('field1', 'field2'),)\n"