Update to conform to django.template.response.TemplateResponse.__init__() signature
This solves a bug relative to the use of MultipleObjectTemplateResponseMixin.render_to_response() while subclassing BaseListView, raising a TypeError Exception ("__init__() got an unexpected keyword argument 'request'")