Update operations.py
fix this error:
  File "/django/db/backends/mysql/operations.py", line 318, in convert_uuidfield_value
    value = uuid.UUID(value)
  File "/usr/lib/python3.8/uuid.py", line 175, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

because our value is equal to blank