Test for i18n bugs when language not found
Test for two edge cases:

If an issued occurred on the filesystem and the .po files are no longer accessible, instead of raising an IOError, fails with ambiguous:

 > AttributeError: 'NoneType' object has no attribute '_info'

Second case: if trying to implement a language that django does not recognize (eg Inuktitut) translations fail with same error.

Related:
https://code.djangoproject.com/ticket/18192
https://groups.google.com/forum/#!msg/django-users/tc0asF6iFBo/u3cBN0SlUl0J