Use get_user_model() instead of user instance to call class method
Using get_user_model() instead of the user instance avoids issues
when a custom user model is provided.

For example, when the user model was overridden, we were seeing
errors like this:

File "[...snip...]/django/contrib/auth/__init__.py", line 111, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
AttributeError: 'MetaDict' object has no attribute 'pk'

Going through the object returned by get_user_model() also matches
what's done in other places in the codebase (for example, in
_get_user_session_key(request)).