Update inline test to explicitly click two delete links
Clicking the delete link in a for loop confuses Selenium because it
could end up removing elements that were still referenced in the
find_elements_by_css_selector() list.

Selenium would raise
StaleElementReferenceException: Message: Element is no longer attached to the DOM