Fixed #37047 -- Fixed crash in Query.orderby_issubset_groupby for descending and random order_by strings.
Run this example:

```python
User.objects.values("is_staff").annotate(latest=Max("date_joined")).order_by("-latest").count()
```

You should see the following exception:

```
django.core.exceptions.FieldError: Cannot resolve keyword '-latest' into field.
```

Regression in 2ce5cb0f7a4618dfdc5f5c10e53e2e9b9543d298.